export const categories = [
  { name: "Fruits and vegetables", value: "fruits-and-vegetables", id: 1 },
  { name: "Meat and poultry", value: "meat-and-poultry", id: 2 },
  { name: "Dairy products", value: "dairy-products", id: 3 },
  { name: "Baked goods", value: "baked-goods", id: 4 },
  { name: "Frozen food", value: "frozen-food", id: 5 },
  { name: "Canned goods", value: "canned-goods", id: 6 },
  { name: "Snacks and beverages", value: "snacks-and-beverages", id: 7 },
  { name: "Cleaning products", value: "cleaning-products", id: 8 },
  { name: "Paper products", value: "paper-products", id: 9 },
  { name: "Laundry products", value: "laundry-products", id: 10 },
  { name: "Personal care products", value: "personal-care-products", id: 11 },
  { name: "Pet supplies", value: "pet-supplies", id: 12 },
  {
    name: "Batteries and lightbulbs",
    value: "batteries-and-lightbulbs",
    id: 13,
  },
  { name: "Hardware", value: "hardware", id: 14 },
  { name: "Televisions", value: "televisions", id: 15 },
  { name: "Computers and laptops", value: "computers-and-laptops", id: 16 },
  { name: "Smartphones and tablets", value: "smartphones-and-tablets", id: 17 },
  { name: "Video games", value: "video-games", id: 18 },
  { name: "Home audio systems", value: "home-audio-systems", id: 19 },
  { name: "Accessories", value: "accessories", id: 20 },
  { name: "Men's clothing", value: "men-clothing", id: 21 },
  { name: "Women's clothing", value: "men-clothing", id: 22 },
  { name: "Children's clothing", value: "men-clothing", id: 23 },
  { name: "Shoes", value: "men-clothing", id: 24 },
];
